server:
  port: 9091

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      department-service:
        register-health-indicator: true
        sliding-window-size: 5
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true


  ratelimiter:
    instances:
      departmentService:
        limit-refresh-period: 10s
        limit-for-period: 5
        timeout-duration: 1s


logging:
  level:
    io.github.resilience4j.circuitbreaker: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
